### ISSUE TITLE
Cake,Stone and Wind creeper causing server crashing.

### ISSUE THREAD

**Issue by chuckjoens11** [T145/ElementalCreepers#18]
### Error Behavior

{Stone,Cake,and Wind Creeper Crash server}
{Please provide a full log of the error}
{You can use a service like [Pastebin](https://pastebin.com/)}
https://pastebin.com/WAARz9dY
https://pastebin.com/UxTNzkrM

### Steps to Reproduce (including precondition)

{Spawning them in and letting em explode}

### Screenshot of this Problem

{Please write here if applicable, else delete this block}

### Your Environment

- OS: {Windows 7}
- Forge version: {14.23.4.2705}
- Mod version: {Release v4.3.3}

**Comment by DrEthan77** [comment]
dark creeper also does this

**Comment by recolic** [comment]
My minecraft server reproduces the bug. Mod version v4.3.3.g5616356, java version 1.8.0_181, CentOS 7.3.

```
[11:18:26] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception                                
net.minecraft.util.ReportedException: Ticking entity                                                                             
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]  
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]     
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]                        
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]                          
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]                                                                   
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.BlockPos$MutableBlockPos.func_189535_a(Lnet/minecraft/entity/Enti
ty;)Lnet/minecraft/util/math/BlockPos$MutableBlockPos;                                                                           
        at T145.elementalcreepers.entities.EntityWindCreeper.createExplosion(EntityWindCreeper.java:38) ~[EntityWindCreeper.class
:?]                                                                                                                              
        at T145.elementalcreepers.entities.base.EntityBaseCreeper.explode(EntityBaseCreeper.java:32) ~[EntityBaseCreeper.class:?]
        at net.minecraft.entity.monster.EntityCreeper.onUpdate(EntityCreeper.java:168) ~[acs.class:?]                            
        at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1990) ~[amu.class:?]                               
        at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]                     
        at net.minecraft.world.World.updateEntity(World.java:1952) ~[amu.class:?]                                                
        at net.minecraft.world.World.redirect$updateEntity$zzi000(World.java:4114) ~[amu.class:?]                                
        at net.minecraft.world.World.updateEntities(World.java:1756) ~[amu.class:?]                                              
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]                                    
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]  
        ... 4 more                                                                                                               
[11:18:26] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /root/minecraft_112/./crash-re
ports/crash-2018-09-27_11.18.26-server.txt                                                                                       
[11:18:26] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server                                                     
```

**Comment by T145** [comment]
Are any of you using SpongeForge? If so, these crashes would make more sense. They occur b/c I use the `MutableBlockPos` class to optimize explosions, and for some reason the class isn't found. I know SpongeForge doesn't have the class for whatever reason (it's included natively in Forge).

**Comment by recolic** [comment]
I'm using a standard Forge server.

**Comment by T145** [comment]
Alright I know how to fix things. I'll fix these bugs, upload a new release and then finish up my breeding system for the next version.

**Comment by tyler489** [comment]
This just crashed my vanill forge server multiple times any update?

**Comment by DrEthan77** [comment]
so how is this going?

**Comment by recolic** [comment]
Here's a workaround: install [badmobs mod](https://www.curseforge.com/minecraft/mc-mods/bad-mobs) (It can be setup as server-only), and edit `badmobs.cfg`:

```
# Configuration file

general {
    # When enabled, the ID of a mob will be shown on it's corrosponding spawn egg. This is used to help you blacklist mobs. [default: true]
    B:addTooltipInfo=true

    # A list of all banned mobs. If a mobs entity name is added to this list, it will not be allowed to spawn in any world. To get the name of an entity, interact with it using the data checker and it's name will be given. [default: [example1], [example2], [example3]]
    S:bannedMobs <
        elementalcreepers:cakecreeper
        elementalcreepers:stonecreeper
        elementalcreepers:windcreeper
        elementalcreepers:reversecreeper
     >

    # When enabled this mod will target mobs that have already spawned. This option must also be enabled to prevent mob spawners from spawning as well. [default: false]
    B:removeAggressively=true

    # While false, this mod will not remove custom named mobs from the game. [default: false]
    B:removeNamedMobs=false
}
```

It actually works for 1.12.2.
